const users =
    [
        {
            id: 1,
            email: "admin@admin.com",
            password: "admin",
            lastname: "Fitsch",
            firstname: "Yann",
            phone: "0676393345",
            birthday: "1988-10-26",
            adress: "36 rue des vosges",
            zipcode: "67118",
            city: "Geispolsheim",
            country: "france",
            dogname: "Burpees",
            dogtype: "eurasier",
            role: 1,
        },
        {
            id: 2,
            email: "user1@user.com",
            password: "user1",
            lastname: "Lafont",
            firstname: "Michelle",
            phone: "0233665599",
            birthday: "1996-07-30",
            adress: "8 rue de Brisach",
            zipcode: "671000",
            city: "Strasbourg",
            country: "france",
            dogname: "Yendi",
            dogtype: "berger australien",
            role: 2,
        },
        {
            id: 3,
            email: "user2@user.com",
            password: "user2",
            lastname: "Wayne",
            firstname: "Bruce",
            phone: "0233553311",
            birthday: "1996-07-30",
            adress: "8 rue de Brisach",
            zipcode: "671000",
            city: "Strasbourg",
            country: "france",
            dogname: "Himba",
            dogtype: "Rodesian",
            role: 2,
        },
        {
            id: 4,
            email: "user3@user.com",
            password: "user4",
            lastname: "Marley",
            firstname: "Bob",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "Medor",
            dogtype: "Caniche",
            role: 2,
        },
        {
            id: 5,
            email: "user5@user.com",
            password: "user5",
            lastname: "Jerome",
            firstname: "banet",
            phone: "0286954455",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "Maya",
            dogtype: "Malinois",
            role: 2,
        },
        {
            id: 6,
            email: "user6@user.com",
            password: "user6",
            lastname: "Leo",
            firstname: "Gabriel",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "Jack",
            dogtype: "Dalmatien",
            role: 2,
        },
        {
            id: 7,
            email: "user7@user.com",
            password: "user7",
            lastname: "Adam",
            firstname: "Bianchi",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "Max",
            dogtype: "Dobermann",
            role: 2,
        },
        {
            id: 8,
            email: "user8@user.com",
            password: "user7",
            lastname: "Arthur",
            firstname: "julio",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "Lucky",
            dogtype: "berger australien",
            role: 2,
        },
        {
            id: 9,
            email: "user9@user.com",
            password: "user9",
            lastname: "Alexis",
            firstname: "dag",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "etoile",
            dogtype: "yorkshire",
            role: 2,
        },
        {
            id: 10,
            email: "user10@user.com",
            password: "user9",
            lastname: "vanessa",
            firstname: "potka",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "ruby",
            dogtype: "Bouvier bernois",
            role: 2,
        },
        {
            id: 11,
            email: "user11@user.com",
            password: "user11",
            lastname: "isabelle",
            firstname: "dank",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "plume",
            dogtype: "Dogue de bordeaux",
            role: 2,
        },
        {
            id: 12,
            email: "user12@user.com",
            password: "user12",
            lastname: "Ginette",
            firstname: "maura",
            phone: "0802050104",
            birthday: "1996-07-30",
            adress: "10 rue de las vegas",
            zipcode: "58212",
            city: "chessy",
            country: "france",
            dogname: "Rebel",
            dogtype: "Eurasier",
            role: 2,
        }
    ]


module.exports = users
